### ISSUE TITLE
Test case not reported when wrapped in FLET

### ISSUE THREAD

**Issue by lukego** [melusina-org/cl-confidence#2]
I discovered a surprising behavior.

I expected these two test cases to be equivalent:

```
(define-testcase ex1 ()
  (assert-condition (error "example") error))

(define-testcase ex2 ()
  (flet ((wrapper ()
           (assert-condition (error "example") error)))
    (wrapper)))
```

but running them provides different reports:

```
> (ex1)
Name: EX1
Total: 1
Success: 1/1 (100%)
Failure: 0/1 (0%)
Condition: 0/1 (0%)
Outcome: Success
#<CONFIDENCE:TESTCASE-RESULT :NAME EX1 :CONFIDENCE::TOTAL 1 :CONFIDENCE::SUCCESS 1 :CONFIDENCE::FAILURE 0 :CONDITION 0 {10026FA963}>

> (ex2)
Name: EX2
Total: 0
Outcome: Success
#<CONFIDENCE:TESTCASE-RESULT :NAME EX2 :CONFIDENCE::TOTAL 0 :CONFIDENCE::SUCCESS 0 :CONFIDENCE::FAILURE 0 :CONDITION 0 {10028CB343}>
```

How come EX1 correctly reports one successful test while EX2 reports no tests?

**Comment by foretspaisibles** [comment]
Thank you, I'll add this to the test suite, it should definitely work as you mean.

If you feel like having a look by yourself, you can start here

  https://github.com/melusina-org/cl-confidence/blob/main/src/testcase.lisp#L185

but I'll give it a close look very soon! Thanks!

**Comment by lukego** [comment]
I see that we are code-walking here. I suppose that's prone to this kind of error. Could this work be done in macro-expansion instead of code-walking somehow to reduce the potential errors surface?

**Comment by lukego** [comment]
My $0.02 is that the simplest and most robust approach is to factor code into plain functions, or failing that into plain macros, and only as a last resort into code-walking. Here we could fix the FLET case by beefing up the code walker but it still would be incomplete e.g. not able to follow subroutine calls.

My gut feeling is that there's a simpler solution here where the restarts etc code that needs to be injected into tests/assertions is written in a plain function and the testcase/assertion macros expand into a thin bit of code calling those functions (and the code walker wouldn't be needed.)

I am no fun, I know, suggesting that Lisp's distinguishing features should be used sparingly if at all :grin:

**Comment by foretspaisibles** [comment]
I rewrote the DEFINE-TESTCASE macro to reduce relying on code walking. It only look for defined ASSERTIONS in code so that conditions are detected when arguments are evaluated. (This is a non-breaking change.)

The new version of DEFINE-TESTCASE relies on signals and handlers to instrument the invocation of defined ASSERTIONS.

https://github.com/melusina-org/cl-confidence/blob/3d1509c19d15f08a6bc6c8e5c24070222d758a9c/testsuite/testcase.lisp#L84
